### ISSUE TITLE
关于如何参与翻译计划

### ISSUE THREAD

**Issue by Win-Man** [mysql2cn/manual56#397]
我想请问一下，如果我想参与翻译计划，我该如何操作。怎么认领翻译的章节，不会和别人冲突？目前有哪些章节是已经完成翻译的？

**Comment by TimoKitty** [comment]
1、查看进度：在milestones里面划分了所有的大的章节，章节中的小节会以issue的方式显现，open的状态为有人认领正在翻译的，closed的为已经翻译好的；
2、参与翻译：首先fork项目，其次根据自己想要翻译的部分建立Issue，在issue中备注完成时间、翻译人姓名和联系方式，并在右侧添加label“正在翻译”和“Milestone"中选择对应的章节；
3、注意事项：由于doc中文件是基于2013年版本的MySQL，因此翻译时需要对应实际版本的章节和标题~~~

**Comment by Win-Man** [comment]
好的，谢谢
