### ISSUE TITLE
Chapter 2 未翻译部分，年后更新

### ISSUE THREAD

**Issue by TimoKitty** [mysql2cn/manual56#419]
2.1.1 Which MySQL Version and Distribution to Install
2.1.2 How to Get MySQL
2.1.3 Verifying Package Integrity Using MD5 Checksums or GnuPG 
2.1.4 Installation Layouts
2.1.5 Compiler-Specific Build Characteristics 
2.2 Installing MySQL on Unix/Linux Using Generic Binaries 
2.3 Installing MySQL on Microsoft Windows 
2.3.1 MySQL Installation Layout on Microsoft Windows 
2.3.2 Choosing An Installation Package 
2.3.3 Installing MySQL on Microsoft Windows Using MySQL Installer 
2.3.4 MySQL Notifier
2.3.5 Installing MySQL on Microsoft Windows Using a noinstall Zip Archive 
2.3.6 Troubleshooting a Microsoft Windows MySQL Server Installation 
2.3.7 Windows Postinstallation Procedures 
2.3.8 Upgrading MySQL on Windows 
2.4 Installing MySQL on OS X 
2.4.1 General Notes on Installing MySQL on OS X 
2.4.2 Installing MySQL on OS X Using Native Packages 
2.4.3 Installing a MySQL Launch Daemon 
2.4.4 Installing and Using the MySQL Preference Pane 
2.5 Installing MySQL on Linux 
2.5.1 Installing MySQL on Linux Using the MySQL Yum Repository 
2.5.2 Replacing a Third-Party Distribution of MySQL Using the MySQL Yum Repository 
2.5.3 Installing MySQL on Linux Using the MySQL APT Repository 
2.11.4 Rebuilding or Repairing Tables or Indexes 
2.11.5 Copying MySQL Databases to Another Machine
其余已有2013年版本翻译，年后更新

**Comment by zhangleqi** [comment]
zhangleqi
zhangleqi12345@gmail.com

2.1
