### ISSUE TITLE
21.30 MySQL Cluster INFORMATION_SCHEMA Tables

### ISSUE THREAD

**Issue by TimoKitty** [mysql2cn/manual56#468]
侯杰（十字螺丝钉）
完成时间：2017年2月15日
联系方式：395062891@qq.com

**Comment by dbhelp** [comment]
翻译完毕，未上传。

**Comment by diguage** [comment]
@dbhelp 发个PR过来吧，我合并进来。

**Comment by dbhelp** [comment]
@diguage  第一次弄，什么是PR？

**Comment by diguage** [comment]
@dbhelp 

你先看看这个 <http://www.diguage.com/archives/42.html> 

再看看 <http://www.worldhello.net/gotgithub/04-work-with-others/010-fork-and-pull.html>

**Comment by dbhelp** [comment]
@diguage  好的 谢谢
